### ISSUE TITLE
everthing is broke

### ISSUE THREAD

**Issue by benjamin238** [MikeModder/007Bot#1]

**Comment by MikeModder** [comment]
Will fix in v2

_Sent from my Samsung SCH-R530U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MikeModder** [comment]
Joking aside, this is a highly WIP bot. Things will be broken. Preferably keep these joke issues to another platform such as Discord. Leave GitHub for actual issues.
