### ISSUE TITLE
Add roleme

### ISSUE THREAD

**Issue by MikeModder** [MikeModder/007Bot#3]
While this would require a per-server config, a roleme system would be really useful.

`]config roleme [add/remove] [role]` and then users could `]roleme [role name]`

**Comment by Artuto** [comment]
I'd say to make it like Spectra.

`]roleme <add|remove> <role>`

**Comment by MikeModder** [comment]
As an addition to this, add an autorole feature, to automatically assign new users a specified role.

**Comment by MikeModder** [comment]
AutoRole is done, Roleme is next. I should just be able to use the same (rough) code so I don't expect this is take very long.

**Comment by MikeModder** [comment]
The current implementation isn't the best, but it works. Done.
